### ISSUE TITLE
Broken in cucumber@0.5.2

### ISSUE THREAD

**Issue by petey** [stjohnjohnson/cucumber-enhancement#1]
Doesn't seem to respect secondary arguments to step definition callbacks.

**Comment by stjohnjohnson** [comment]
Looking at what has changed here: https://github.com/cucumber/cucumber-js/compare/v0.4.2...v0.5.2

**Comment by stjohnjohnson** [comment]
Looks like it could be: https://github.com/cucumber/cucumber-js/commit/cc8a44eab2368140c4ec8c3007dcee55e4dc34dc
